#!/bin/bash
h5pfc -c -CB -heap-arrays -qopenmp -mkl -fpic -mcmodel=large -i8 global_param.f90
h5pfc -c -CB -heap-arrays -qopenmp -mkl -fpic -mcmodel=large -i8 load_hamiltonian.f90
h5pfc -c -CB -heap-arrays -qopenmp -mkl -fpic -mcmodel=large -i8 dyn.f90
h5pfc -CB -heap-arrays -qopenmp -mkl -fpic -mcmodel=large -i8 load_hamiltonian.o global_param.o -o Load.exe
h5pfc -CB -heap-arrays -qopenmp -mkl -fpic -mcmodel=large -i8 dyn.o global_param.o -o Run.exe

rm *.o *.mod
